name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      env:
        OPENAI_API_KEY: "sk-mock-key-for-testing-only"
      run: |
        mkdir -p reports/coverage
        python -m pytest --cov=. --cov-report=term-missing --cov-report=xml:reports/coverage/coverage.xml
        
    - name: Update coverage Gist
      if: github.ref == 'refs/heads/main'
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python scripts/update_coverage_gist.py
        python scripts/generate_coverage_badge.py 