name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage xml
        coverage html
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: htmlcov/
        
    - name: Generate coverage badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: coverage
        LABEL: coverage
        STATUS: ${{ steps.coverage.outputs.coverage }}
        COLOR: ${{ steps.coverage.outputs.color }}
        GIST_FILENAME: coverage.json
        GIST_ID: ${{ secrets.COVERAGE_GIST_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 