name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14-arm64
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      env:
        OPENAI_API_KEY: sk-mock-key-for-testing-only
        CI: true
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests
      env:
        OPENAI_API_KEY: sk-mock-key-for-testing-only
        CI: true
      run: |
        mkdir -p reports/coverage
        python -m pytest --cov=. --cov-report=term-missing --cov-report=xml:reports/coverage/coverage.xml
        
    - name: Update coverage Gist
      if: github.ref == 'refs/heads/main'
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python scripts/update_coverage_gist.py
        python scripts/generate_coverage_badge.py 